modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-amplifieddimension/issues"
license = "ARR"

[[mods]]
modId = "amplifieddimension"
version = "${version}"
displayName = "Amplified Dimension"
authors = "mahmudindev"
description = '''
Add amplified as separate dimension.
'''
logoFile = "assets/amplifieddimension/icon.png"

[[dependencies.amplifieddimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.amplifieddimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.amplifieddimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "amplifieddimension.mixins.json"
